# Basic

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3, 5)

In [6]:
a.ndim

2

# Array Creation

In [7]:
a = np.array([2,3,4])

In [8]:
a

array([2, 3, 4])

In [9]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [13]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [14]:
b = np.array([[1.5,2,3], (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [12]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [16]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [18]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [19]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Basic Operations

In [22]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [23]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [24]:
a - b

array([20, 29, 38, 47])

In [25]:
b**2

array([0, 1, 4, 9])

In [26]:
10*np.cos(a)

array([ 4.08082062,  1.5425145 , -6.66938062,  9.64966028])

In [27]:
a > 15

array([ True,  True,  True,  True], dtype=bool)

In [30]:
A = np.array( [[1,1],
...             [0,1]] )
A

array([[1, 1],
       [0, 1]])

In [31]:
B = np.array( [[2,0],
...             [3,4]] )
B

array([[2, 0],
       [3, 4]])

In [32]:
A*B

array([[2, 0],
       [0, 4]])

In [33]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [34]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [38]:
b += a
b

array([ 80, 121, 162, 203])

In [39]:
a.mean()

35.0

In [40]:
np.exp(B)

array([[  7.3890561 ,   1.        ],
       [ 20.08553692,  54.59815003]])

In [41]:
a = np.arange(10)**3

In [42]:
a[2:5]

array([ 8, 27, 64])

In [43]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [44]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

# Shape Manipulation

In [54]:
a = np.floor(10*np.random.random((3,4)))

In [55]:
a.shape

(3, 4)

In [56]:
a.ravel()

array([ 2.,  7.,  8.,  9.,  8.,  6.,  6.,  4.,  4.,  3.,  0.,  1.])

In [57]:
a.reshape(6, 2)

array([[ 2.,  7.],
       [ 8.,  9.],
       [ 8.,  6.],
       [ 6.,  4.],
       [ 4.,  3.],
       [ 0.,  1.]])

In [58]:
a.T

array([[ 2.,  8.,  4.],
       [ 7.,  6.,  3.],
       [ 8.,  6.,  0.],
       [ 9.,  4.,  1.]])

In [59]:
a.resize((6, 2))

In [60]:
a

array([[ 2.,  7.],
       [ 8.,  9.],
       [ 8.,  6.],
       [ 6.,  4.],
       [ 4.,  3.],
       [ 0.,  1.]])

# Stacking together different arrays

In [63]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 8.,  7.],
       [ 6.,  9.]])

In [64]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 8.,  8.],
       [ 9.,  1.]])

In [65]:
np.vstack((a,b))

array([[ 8.,  7.],
       [ 6.,  9.],
       [ 8.,  8.],
       [ 9.,  1.]])

In [66]:
np.hstack((a,b))

array([[ 8.,  7.,  8.,  8.],
       [ 6.,  9.,  9.,  1.]])

# Splitting one array into several smaller ones

In [67]:
a = np.floor(10*np.random.random((2,12)))

In [68]:
a

array([[ 5.,  0.,  3.,  1.,  6.,  4.,  1.,  9.,  2.,  8.,  8.,  4.],
       [ 2.,  6.,  3.,  0.,  3.,  4.,  0.,  7.,  3.,  3.,  7.,  0.]])

In [69]:
np.hsplit(a,3) 

[array([[ 5.,  0.,  3.,  1.],
        [ 2.,  6.,  3.,  0.]]), array([[ 6.,  4.,  1.,  9.],
        [ 3.,  4.,  0.,  7.]]), array([[ 2.,  8.,  8.,  4.],
        [ 3.,  3.,  7.,  0.]])]

In [70]:
t = np.hsplit(a,3) 

In [75]:
print(t[1])

[[ 6.  4.  1.  9.]
 [ 3.  4.  0.  7.]]


# Copies and Views

In [76]:
a = np.arange(12)

In [77]:
b = a

In [78]:
b is a

True

In [79]:
c = a.view()

In [80]:
c is a

False

In [81]:
c.base is a

True

In [86]:
a = np.arange(12)
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
s = a[ : , 1:3]
s[:] = 10 
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [88]:
d = a.copy() 
d is a

False

In [89]:
d.base is a

False

In [90]:
d[0,0] = 9999

In [91]:
d

array([[9999,   10,   10,    3],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])

In [92]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [93]:
a.sort()

In [94]:
a

array([[ 0,  3, 10, 10],
       [ 4,  7, 10, 10],
       [ 8, 10, 10, 11]])

# Fancy indexing and index tricks

In [98]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [96]:
i = np.array( [ 1,1,3,8,5 ] )  

In [97]:
a[i]

array([ 1,  1,  9, 64, 25])

In [99]:
j = range(1,3)

In [100]:
a[j]

array([1, 4])

In [101]:
b = a > 4

In [102]:
b

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)

In [103]:
a[b]

array([  9,  16,  25,  36,  49,  64,  81, 100, 121])

In [104]:
a[b] = 0 

In [105]:
a

array([0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
a = np.array([1, 3])

In [113]:
a

array([1, 3])

In [114]:
b = np.array([[1], [2]])

In [115]:
b

array([[1],
       [2]])

In [116]:
a * b

array([[1, 3],
       [2, 6]])

# Linear Algebra

In [117]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [119]:
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [120]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [121]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [122]:
np.trace(a) 

5.0

In [124]:
help(np.trace)

Help on function trace in module numpy.core.fromnumeric:

trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
    Return the sum along diagonals of the array.
    
    If `a` is 2-D, the sum along its diagonal with the given offset
    is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.
    
    If `a` has more than two dimensions, then the axes specified by axis1 and
    axis2 are used to determine the 2-D sub-arrays whose traces are returned.
    The shape of the resulting array is the same as that of `a` with `axis1`
    and `axis2` removed.
    
    Parameters
    ----------
    a : array_like
        Input array, from which the diagonals are taken.
    offset : int, optional
        Offset of the diagonal from the main diagonal. Can be both positive
        and negative. Defaults to 0.
    axis1, axis2 : int, optional
        Axes to be used as the first and second axis of the 2-D sub-arrays
        from which the diagonals should be taken. Defaults are the 