# Basic

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3, 5)

In [6]:
a.ndim

2

# Array Creation

In [7]:
a = np.array([2,3,4])

In [8]:
a

array([2, 3, 4])

In [9]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [13]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [14]:
b = np.array([[1.5,2,3], (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [12]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [16]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [18]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [19]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Basic Operations

In [22]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [23]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [24]:
a - b

array([20, 29, 38, 47])

In [25]:
b**2

array([0, 1, 4, 9])

In [26]:
10*np.cos(a)

array([ 4.08082062,  1.5425145 , -6.66938062,  9.64966028])

In [27]:
a > 15

array([ True,  True,  True,  True], dtype=bool)

In [30]:
A = np.array( [[1,1],
...             [0,1]] )
A

array([[1, 1],
       [0, 1]])

In [31]:
B = np.array( [[2,0],
...             [3,4]] )
B

array([[2, 0],
       [3, 4]])

In [32]:
A*B

array([[2, 0],
       [0, 4]])

In [33]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [34]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [38]:
b += a
b

array([ 80, 121, 162, 203])

In [39]:
a.mean()

35.0

In [40]:
np.exp(B)

array([[  7.3890561 ,   1.        ],
       [ 20.08553692,  54.59815003]])

In [41]:
a = np.arange(10)**3

In [42]:
a[2:5]

array([ 8, 27, 64])

In [43]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [44]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])